// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFund(arg1:models.Fund):Promise<void>;

export function AddPosition(arg1:models.FundPosition):Promise<void>;

export function BatchUpdateFunds():Promise<void>;

export function CalculateAllGroupsValue():Promise<Record<string, models.GroupSummary>>;

export function CalculateEstimateValue(arg1:string,arg2:number,arg3:number):Promise<models.FundValue>;

export function CalculateGroupValue(arg1:string):Promise<models.GroupSummary>;

export function CalculatePositionValue(arg1:string):Promise<models.FundValue>;

export function DeletePosition(arg1:string):Promise<void>;

export function GetAllFunds():Promise<Array<models.Fund>>;

export function GetAllGroups():Promise<Array<string>>;

export function GetAllPositions():Promise<Array<models.FundPosition>>;

export function GetClientCount():Promise<number>;

export function GetConfig(arg1:string):Promise<string>;

export function GetFund(arg1:string):Promise<models.Fund>;

export function GetFundHistory(arg1:string,arg2:number):Promise<Array<models.FundValue>>;

export function GetFundInfo(arg1:string):Promise<models.Fund>;

export function GetGroupPositions(arg1:string):Promise<Array<models.FundPosition>>;

export function GetGroupSummary(arg1:string):Promise<models.GroupSummary>;

export function GetPortfolioPerformance():Promise<Record<string, any>>;

export function GetPortfolioSummary():Promise<models.PortfolioSummary>;

export function GetPosition(arg1:string):Promise<models.FundPosition>;

export function GetPositionDetails(arg1:string):Promise<Record<string, any>>;

export function GetRealTimeFundHistory(arg1:string,arg2:number):Promise<Array<models.FundValue>>;

export function GetRealTimeFundValue(arg1:string):Promise<models.FundValue>;

export function GetRealTimeGroupSummary(arg1:string):Promise<models.GroupSummary>;

export function GetRealTimeGroupValues():Promise<Record<string, models.GroupSummary>>;

export function GetRealTimeSummary():Promise<models.PortfolioSummary>;

export function GetRefreshInterval():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function IsRealTimeRunning():Promise<boolean>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetRefreshInterval(arg1:number):Promise<void>;

export function StartRealTimeService():Promise<void>;

export function StopRealTimeService():Promise<void>;

export function UpdatePositionCostPrice(arg1:string,arg2:number):Promise<void>;

export function UpdatePositionGroup(arg1:string,arg2:string):Promise<void>;

export function UpdatePositionShares(arg1:string,arg2:number):Promise<void>;
