// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFund(arg1) {
  return window['go']['main']['App']['AddFund'](arg1);
}

export function AddPosition(arg1) {
  return window['go']['main']['App']['AddPosition'](arg1);
}

export function BatchUpdateFunds() {
  return window['go']['main']['App']['BatchUpdateFunds']();
}

export function CalculateAllGroupsValue() {
  return window['go']['main']['App']['CalculateAllGroupsValue']();
}

export function CalculateEstimateValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateEstimateValue'](arg1, arg2, arg3);
}

export function CalculateGroupValue(arg1) {
  return window['go']['main']['App']['CalculateGroupValue'](arg1);
}

export function CalculatePositionValue(arg1) {
  return window['go']['main']['App']['CalculatePositionValue'](arg1);
}

export function DeletePosition(arg1) {
  return window['go']['main']['App']['DeletePosition'](arg1);
}

export function GetAllFunds() {
  return window['go']['main']['App']['GetAllFunds']();
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function GetAllPositions() {
  return window['go']['main']['App']['GetAllPositions']();
}

export function GetClientCount() {
  return window['go']['main']['App']['GetClientCount']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetFund(arg1) {
  return window['go']['main']['App']['GetFund'](arg1);
}

export function GetFundHistory(arg1, arg2) {
  return window['go']['main']['App']['GetFundHistory'](arg1, arg2);
}

export function GetFundInfo(arg1) {
  return window['go']['main']['App']['GetFundInfo'](arg1);
}

export function GetGroupPositions(arg1) {
  return window['go']['main']['App']['GetGroupPositions'](arg1);
}

export function GetGroupSummary(arg1) {
  return window['go']['main']['App']['GetGroupSummary'](arg1);
}

export function GetPortfolioPerformance() {
  return window['go']['main']['App']['GetPortfolioPerformance']();
}

export function GetPortfolioSummary() {
  return window['go']['main']['App']['GetPortfolioSummary']();
}

export function GetPosition(arg1) {
  return window['go']['main']['App']['GetPosition'](arg1);
}

export function GetPositionDetails(arg1) {
  return window['go']['main']['App']['GetPositionDetails'](arg1);
}

export function GetRealTimeFundHistory(arg1, arg2) {
  return window['go']['main']['App']['GetRealTimeFundHistory'](arg1, arg2);
}

export function GetRealTimeFundValue(arg1) {
  return window['go']['main']['App']['GetRealTimeFundValue'](arg1);
}

export function GetRealTimeGroupSummary(arg1) {
  return window['go']['main']['App']['GetRealTimeGroupSummary'](arg1);
}

export function GetRealTimeGroupValues() {
  return window['go']['main']['App']['GetRealTimeGroupValues']();
}

export function GetRealTimeSummary() {
  return window['go']['main']['App']['GetRealTimeSummary']();
}

export function GetRefreshInterval() {
  return window['go']['main']['App']['GetRefreshInterval']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRealTimeRunning() {
  return window['go']['main']['App']['IsRealTimeRunning']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetRefreshInterval(arg1) {
  return window['go']['main']['App']['SetRefreshInterval'](arg1);
}

export function StartRealTimeService() {
  return window['go']['main']['App']['StartRealTimeService']();
}

export function StopRealTimeService() {
  return window['go']['main']['App']['StopRealTimeService']();
}

export function UpdatePositionCostPrice(arg1, arg2) {
  return window['go']['main']['App']['UpdatePositionCostPrice'](arg1, arg2);
}

export function UpdatePositionGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdatePositionGroup'](arg1, arg2);
}

export function UpdatePositionShares(arg1, arg2) {
  return window['go']['main']['App']['UpdatePositionShares'](arg1, arg2);
}
